// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDACEgLSa24RlJ0nufPar9MnbkZ00_qnVg',
    appId: '1:211577314132:web:100ff2fb13daaf3c6686c1',
    messagingSenderId: '211577314132',
    projectId: 'keikofoodreview',
    authDomain: 'keikofoodreview.firebaseapp.com',
    storageBucket: 'keikofoodreview.firebasestorage.app',
    measurementId: 'G-RRYNYK2CQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEvewI-S0lMfgnE2l4ZosvNd2lSL6nxF0',
    appId: '1:211577314132:android:4e2ebcacded861b56686c1',
    messagingSenderId: '211577314132',
    projectId: 'keikofoodreview',
    storageBucket: 'keikofoodreview.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSc2AXSxBx-5_zsAdDEB3UQ_1ZY1kjSXY',
    appId: '1:211577314132:ios:193d456f473d06536686c1',
    messagingSenderId: '211577314132',
    projectId: 'keikofoodreview',
    storageBucket: 'keikofoodreview.firebasestorage.app',
    iosBundleId: 'com.example.keikoFoodReview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSc2AXSxBx-5_zsAdDEB3UQ_1ZY1kjSXY',
    appId: '1:211577314132:ios:193d456f473d06536686c1',
    messagingSenderId: '211577314132',
    projectId: 'keikofoodreview',
    storageBucket: 'keikofoodreview.firebasestorage.app',
    iosBundleId: 'com.example.keikoFoodReview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDACEgLSa24RlJ0nufPar9MnbkZ00_qnVg',
    appId: '1:211577314132:web:ab436d3359abb76c6686c1',
    messagingSenderId: '211577314132',
    projectId: 'keikofoodreview',
    authDomain: 'keikofoodreview.firebaseapp.com',
    storageBucket: 'keikofoodreview.firebasestorage.app',
    measurementId: 'G-7B2H47L6RG',
  );
}
